### PR TITLE
[EAM-3113] Activity update confirm delete checklists

### PR DESCRIPTION
**Pull request by purquijo**

### CODE REVIEW

**Comment by purquijo** [comment]
The `pom.xml` should be updated once the new WSHUH version is released.

**Comment by purquijo** [comment]
@ricardo-j-almeida solved

**Comment by ricardo-j-almeida** [comment]
There's a more recent version now Pablo, please update the pom.xml

**Comment by purquijo** [comment]
@ricardo-j-almeida done

**Pull request merged**
